//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus_Social_Network.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddClass
    {
        public int Id { get; set; }
        public string ClassName { get; set; }
        public string ClassCapacity { get; set; }
    }
}
